"""Research workflow — INSPIRATION.md scaffold and validation."""

from __future__ import annotations

import re
from pathlib import Path

from ..constants import RESEARCH_INSPIRATION

INSPIRATION_TEMPLATE = """# Design Inspiration

> Patterns and principles only — not assets to copy.  
> Generated by `graphcraft aesthetic research init`.

**Date:** YYYY-MM-DD  
**Project profile:** (mobile-app | mobile-game)  
**Linked brief:** handoff/AESTHETIC_BRIEF.md

---

## Research queries (max 5)

1. 
2. 
3. 

---

## Patterns observed

### Layout
- 

### Typography & hierarchy
- 

### Color & mood
- 

### Motion & interaction
- 

---

## References (URLs — patterns, not clones)

| Source | Pattern extracted | Risk notes |
|--------|-------------------|------------|
| | | |

---

## Style direction notes

| Direction | Mood | Marketing fit | Usability fit |
|-----------|------|---------------|---------------|
| 1 | | | |
| 2 | | | |
| 3 | | | |

**Selected:** style:...

---

## Accessibility floors

- Contrast minimum: 4.5:1 (WCAG AA body text)
- Touch target minimum: 44px
- Safe area: required for notched devices

---

## Avoid

- Trademark / clone risk:
- 

---

## Handoff checklist

- [ ] AESTHETIC_BRIEF.md status: Ready for Designer
- [ ] `graphcraft.config.yaml` design.style updated
- [ ] `graphcraft design evaluate` PASS or WARN with notes
"""

_REQUIRED_SECTIONS = (
    "## Research queries",
    "## Patterns observed",
    "## References",
    "## Style direction notes",
    "## Accessibility floors",
    "## Avoid",
)


def init_inspiration(root: Path, *, force: bool = False) -> Path:
    root = root.resolve()
    research_dir = root / "research"
    research_dir.mkdir(parents=True, exist_ok=True)
    path = root / RESEARCH_INSPIRATION
    if path.is_file() and not force:
        return path
    path.write_text(INSPIRATION_TEMPLATE, encoding="utf-8")
    return path


def validate_inspiration(root: Path) -> list[str]:
    path = root / RESEARCH_INSPIRATION
    issues: list[str] = []
    if not path.is_file():
        issues.append(f"Missing {RESEARCH_INSPIRATION} — run: graphcraft aesthetic research init")
        return issues
    text = path.read_text(encoding="utf-8")
    for section in _REQUIRED_SECTIONS:
        if section not in text:
            issues.append(f"INSPIRATION missing section: {section}")
    if "**Date:** YYYY-MM-DD" in text:
        issues.append("INSPIRATION still has placeholder date YYYY-MM-DD")
    queries_block = text.split("## Patterns observed")[0] if "## Patterns observed" in text else text
    if not re.search(r"1\.\s+\S", queries_block):
        issues.append("Research queries appear empty (fill at least one query)")
    return issues
