"""Research workflow — INSPIRATION.md scaffold, validation, and automated run."""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path
from typing import Any, Callable

from ..constants import RESEARCH_INSPIRATION
from .config_loader import aesthetic_settings, load_config
from .query_builder import build_research_queries
from .synthesize import detect_risk_notes, suggest_style_directions, synthesize_patterns
from .web_search import SearchResult, doctor_search, search_queries

INSPIRATION_TEMPLATE = """# Design Inspiration

> Patterns and principles only — not assets to copy.  
> Generated by `graphcraft aesthetic research init`.

**Date:** YYYY-MM-DD  
**Project profile:** (mobile-app | mobile-game)  
**Linked brief:** handoff/AESTHETIC_BRIEF.md

---

## Research queries (max 5)

1. 
2. 
3. 

---

## Patterns observed

### Layout
- 

### Typography & hierarchy
- 

### Color & mood
- 

### Motion & interaction
- 

---

## References (URLs — patterns, not clones)

| Source | Pattern extracted | Risk notes |
|--------|-------------------|------------|
| | | |

---

## Style direction notes

| Direction | Mood | Marketing fit | Usability fit |
|-----------|------|---------------|---------------|
| 1 | | | |
| 2 | | | |
| 3 | | | |

**Selected:** style:...

---

## Accessibility floors

- Contrast minimum: 4.5:1 (WCAG AA body text)
- Touch target minimum: 44px
- Safe area: required for notched devices

---

## Avoid

- Trademark / clone risk:
- 

---

## Handoff checklist

- [ ] AESTHETIC_BRIEF.md status: Ready for Designer
- [ ] `graphcraft.config.yaml` design.style updated
- [ ] `graphcraft design evaluate` PASS or WARN with notes
"""

_REQUIRED_SECTIONS = (
    "## Research queries",
    "## Patterns observed",
    "## References",
    "## Style direction notes",
    "## Accessibility floors",
    "## Avoid",
)


def init_inspiration(root: Path, *, force: bool = False) -> Path:
    root = root.resolve()
    research_dir = root / "research"
    research_dir.mkdir(parents=True, exist_ok=True)
    path = root / RESEARCH_INSPIRATION
    if path.is_file() and not force:
        return path
    path.write_text(INSPIRATION_TEMPLATE, encoding="utf-8")
    return path


def validate_inspiration(root: Path) -> list[str]:
    path = root / RESEARCH_INSPIRATION
    issues: list[str] = []
    if not path.is_file():
        issues.append(f"Missing {RESEARCH_INSPIRATION} — run: graphcraft aesthetic research init")
        return issues
    text = path.read_text(encoding="utf-8")
    for section in _REQUIRED_SECTIONS:
        if section not in text:
            issues.append(f"INSPIRATION missing section: {section}")
    if "**Date:** YYYY-MM-DD" in text:
        issues.append("INSPIRATION still has placeholder date YYYY-MM-DD")
    queries_block = text.split("## Patterns observed")[0] if "## Patterns observed" in text else text
    if not re.search(r"1\.\s+\S", queries_block):
        issues.append("Research queries appear empty (fill at least one query)")
    ref_block = text.split("## Style direction notes")[0] if "## Style direction notes" in text else text
    if (
        "graphcraft aesthetic research run" in text
        and "| http" not in ref_block
        and "| https" not in ref_block
    ):
        issues.append("References table has no URLs — re-run research or add sources")
    return issues


def _profile_label(root: Path) -> str:
    config = load_config(root)
    return str(config.get("profile") or "mobile-app")


def render_inspiration(
    root: Path,
    *,
    queries: list[str],
    results: list[SearchResult],
    patterns: dict[str, list[str]],
    directions: list[dict[str, str]],
    risk_notes: list[str],
) -> str:
    today = date.today().isoformat()
    profile = _profile_label(root)
    selected = directions[0]["id"] if directions else "style:minimal-dark"

    query_lines = "\n".join(f"{i}. {q}" for i, q in enumerate(queries, 1))
    for i in range(len(queries) + 1, 4):
        query_lines += f"\n{i}. "

    def bullets(items: list[str]) -> str:
        return "\n".join(f"- {line}" for line in items[:5])

    ref_rows = []
    for item in results[:12]:
        pattern = item.snippet[:80] + ("…" if len(item.snippet) > 80 else "")
        risk = "review branding" if "brand" in item.title.lower() else "pattern only"
        ref_rows.append(f"| {item.url} | {pattern} | {risk} |")
    if not ref_rows:
        ref_rows.append("| | | |")

    dir_rows = []
    for i, d in enumerate(directions[:3], 1):
        dir_rows.append(
            f"| {i} | {d.get('mood', '—')} | {d.get('marketing', '—')} | {d.get('usability', '—')} |"
        )

    return f"""# Design Inspiration

> Patterns and principles only — not assets to copy.  
> Generated by `graphcraft aesthetic research run`.

**Date:** {today}  
**Project profile:** {profile}  
**Linked brief:** handoff/AESTHETIC_BRIEF.md

---

## Research queries (max 5)

{query_lines}

---

## Patterns observed

### Layout
{bullets(patterns.get("layout", []))}

### Typography & hierarchy
{bullets(patterns.get("typography", []))}

### Color & mood
{bullets(patterns.get("color", []))}

### Motion & interaction
{bullets(patterns.get("motion", []))}

---

## References (URLs — patterns, not clones)

| Source | Pattern extracted | Risk notes |
|--------|-------------------|------------|
{chr(10).join(ref_rows)}

---

## Style direction notes

| Direction | Mood | Marketing fit | Usability fit |
|-----------|------|---------------|---------------|
{chr(10).join(dir_rows)}

**Selected:** {selected}

---

## Accessibility floors

- Contrast minimum: 4.5:1 (WCAG AA body text)
- Touch target minimum: 44px
- Safe area: required for notched devices

---

## Avoid

{chr(10).join(f'- {note}' for note in risk_notes)}

---

## Handoff checklist

- [ ] AESTHETIC_BRIEF.md status: Ready for Designer
- [ ] `graphcraft.config.yaml` design.style updated
- [ ] `graphcraft design evaluate` PASS or WARN with notes
"""


def doctor_research(root: Path, *, offline: bool = False) -> list[str]:
    issues: list[str] = []
    config = load_config(root)
    aesthetic = aesthetic_settings(config)
    if not aesthetic.get("research_enabled", True):
        issues.append("aesthetic.research_enabled is false in graphcraft.config.yaml")

    queries = build_research_queries(root, max_queries=1)
    if not queries:
        issues.append("Could not build any research queries from config/brief")

    issues.extend(doctor_search(offline=offline))
    return issues


def run_research(
    root: Path,
    *,
    force: bool = False,
    offline: bool = False,
    max_queries: int = 5,
    max_results_per_query: int = 3,
    provider: Callable[[str, int], list[SearchResult]] | None = None,
) -> tuple[Path, list[str]]:
    """Run automated research and write INSPIRATION.md. Returns (path, warnings)."""
    root = root.resolve()
    path = root / RESEARCH_INSPIRATION
    warnings: list[str] = []

    config = load_config(root)
    aesthetic = aesthetic_settings(config)
    if not aesthetic.get("research_enabled", True) and not force:
        raise RuntimeError(
            "aesthetic.research_enabled is false — pass --force to run anyway"
        )

    if path.is_file() and not force:
        raise FileExistsError(
            f"{RESEARCH_INSPIRATION} already exists — use --force to overwrite"
        )

    max_q = int(aesthetic.get("max_research_queries") or max_queries)
    queries = build_research_queries(root, max_queries=max_q)
    if not queries:
        raise RuntimeError("No research queries could be built")

    results = search_queries(
        queries,
        max_results_per_query=max_results_per_query,
        offline=offline,
        provider=provider,
    )
    if not results:
        warnings.append("No web results returned — INSPIRATION written from query templates only")
        results = []

    patterns = synthesize_patterns(results) if results else {
        k: ["Run with live network search for richer patterns."] for k in ("layout", "typography", "color", "motion")
    }
    directions = suggest_style_directions(root, results)
    risk_notes = detect_risk_notes(results) if results else [
        "Avoid pixel-level clones of branded apps; extract layout and flow patterns only."
    ]

    (root / "research").mkdir(parents=True, exist_ok=True)
    content = render_inspiration(
        root,
        queries=queries,
        results=results,
        patterns=patterns,
        directions=directions,
        risk_notes=risk_notes,
    )
    path.write_text(content, encoding="utf-8")
    return path, warnings
